package com.ek.client.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2015-05-15T10:25:36.080+08:00
 * Generated source version: 2.7.7
 * 
 */
@WebService(targetNamespace = "http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cp_mdm_sdh_get_data_pkg2/", name = "CP_MDM_SDH_GET_DATA_PKG2_PortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CPMDMSDHGETDATAPKG2PortType {

    @WebResult(name = "OutputParameters", targetNamespace = "http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cp_mdm_sdh_get_data_pkg2/export_cp_sdh_info/", partName = "body")
    @WebMethod(operationName = "EXPORT_CP_SDH_INFO", action = "EXPORT_CP_SDH_INFO")
    public OutputParameters exportCPSDHINFO(
        @WebParam(partName = "header", name = "SOAHeader", targetNamespace = "http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cp_mdm_sdh_get_data_pkg2/", header = true)
        SOAHeader header,
        @WebParam(partName = "body", name = "InputParameters", targetNamespace = "http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cp_mdm_sdh_get_data_pkg2/export_cp_sdh_info/")
        InputParameters body
    ) throws ISGServiceFaultMessage;
}
