
package com.ek.client.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.7
 * 2015-05-15T10:25:36.070+08:00
 * Generated source version: 2.7.7
 */

@WebFault(name = "ISGServiceFault", targetNamespace = "http://xmlns.oracle.com/isg/servicefault")
public class ISGServiceFaultMessage extends Exception {
    
    private com.ek.client.service.ISGServiceFault isgServiceFault;

    public ISGServiceFaultMessage() {
        super();
    }
    
    public ISGServiceFaultMessage(String message) {
        super(message);
    }
    
    public ISGServiceFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public ISGServiceFaultMessage(String message, com.ek.client.service.ISGServiceFault isgServiceFault) {
        super(message);
        this.isgServiceFault = isgServiceFault;
    }

    public ISGServiceFaultMessage(String message, com.ek.client.service.ISGServiceFault isgServiceFault, Throwable cause) {
        super(message, cause);
        this.isgServiceFault = isgServiceFault;
    }

    public com.ek.client.service.ISGServiceFault getFaultInfo() {
        return this.isgServiceFault;
    }
}
