package com.ek.client.services.example;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2015-05-15T10:55:06.785+08:00
 * Generated source version: 2.7.7
 * 
 */
@WebService(targetNamespace = "http://jeeek-dp/", name = "ExampleService")
public interface ExampleService {

    @WebResult(name = "password", targetNamespace = "")
    @RequestWrapper(localName = "getStr", targetNamespace = "http://jeeek-dp/")
    @WebMethod(action = "http://jeeek-dp/ExampleService/getStr")
    @ResponseWrapper(localName = "getStrResponse", targetNamespace = "http://jeeek-dp/")
    public User getStr(
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name
    );
}
